### ISSUE TITLE
一点点小建议。

### ISSUE THREAD

**Issue by wangcaohong** [hcsp/java-island#1]
java-island 倒数第二步，实际上不需要重启，若在配置环境变量的时候已经打开控制台，只需要配置完后将控制台关了重开即可开始检验是否配置成功，而且还需要验证下 javac 这个很重要的编译命令，很多时候 java -version 可以执行，而 javac 会因为配置不对导致无法执行。

**Comment by blindpirate** [comment]
@Crowch 感谢反馈。这是一个可能比你想象中复杂的问题。

[这篇文章](https://serverfault.com/questions/8855/how-do-you-add-a-windows-environment-variable-without-rebooting)提到：

> However, note that modifications to the environment variables do not result in immediate change. For example, if you start another Command Prompt after making the changes, the environment variables will reflect the previous (not the current) values. The changes do not take effect until you log off and then log back on.

至少在早期版本的Windows NT中，环境变量无法立即生效。到底有多早呢？我不知道。另外还有一些用户报告在Windows 8中也观察到了这个现象：https://superuser.com/questions/593949/why-wont-my-windows-8-command-line-update-its-path 这个用户甚至自己写了一个程序来处理`WM_SETTINGCHANGE `消息。有人指出似乎是Windows的一个问题：https://support.microsoft.com/en-us/help/2913826/user-variables-are-not-resolved-correctly-in-windows

我认为在面对小白用户时，令其重启是成本最低的方式，并且没有什么副作用。题目中要求`java`的输出并不是为了未来在命令行中运行，而是为了验证`JDK`已经正确地安装。以后的几乎所有题目都是使用IDE的，验证`javac`关系不大。另外，JDK9+已经没有JRE了，更加没有必要验证`javac`了。
